version: '3.9'
services:
  soundproof:
    image: discord-bot-soundproof:latest
    container_name: soundproof-bot
    ports:
      - "3001:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped

  listen:
    image: discord-bot-lkeff-listen:latest
    container_name: listen-bot
    ports:
      - "3002:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped

  airhornbot:
    image: discord-bot-airhornbot:latest
    container_name: airhornbot
    ports:
      - "3003:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped

  discord-aibot:
    image: discord-bot-discord-aibot:latest
    container_name: discord-aibot
    ports:
      - "3004:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped

  lastfm:
    image: discord-bot-lastfm-client:latest
    container_name: lastfm-bot
    ports:
      - "3005:3000"
    environment:
      - DISCORD_TOKEN=${DISCORD_TOKEN}
    restart: unless-stopped
