import { Rig } from "../rig";

const lua = (text: string) => JSON.stringify(text);

const FIND_INPUT = `
local function midi_input(name)
  for i = 0, reaper.GetNumMIDIInputs() - 1 do
    local ok, port = reaper.GetMIDIInputName(i, "")
    if ok and port:lower():find(name:lower(), 1, true) then return i end
  end
  return 63 -- all inputs
end
`;

// ReaScript (Actions > Show action list > New action > Load ReaScript) that builds the live rig:
// one folder per group, one record-armed, monitored track per section listening on its MIDI port and channel.
export function liveRigScript(rig: Rig): string {
  const groups = new Map<string, [string, Rig["sections"][string]][]>();
  for (const entry of Object.entries(rig.sections)) groups.set(entry[1].group, [...(groups.get(entry[1].group) ?? []), entry]);
  const lines = [
    "-- Generated by lastfm-companion: npm run studio reaper",
    "reaper.Undo_BeginBlock()",
    FIND_INPUT,
    "local function add(name, depth, port, channel)",
    "  local index = reaper.CountTracks(0)",
    "  reaper.InsertTrackAtIndex(index, true)",
    "  local track = reaper.GetTrack(0, index)",
    "  reaper.GetSetMediaTrackInfo_String(track, \"P_NAME\", name, true)",
    "  reaper.SetMediaTrackInfo_Value(track, \"I_FOLDERDEPTH\", depth)",
    "  if port then",
    "    reaper.SetMediaTrackInfo_Value(track, \"I_RECINPUT\", 4096 + midi_input(port) * 32 + channel)",
    "    reaper.SetMediaTrackInfo_Value(track, \"I_RECARM\", 1)",
    "    reaper.SetMediaTrackInfo_Value(track, \"I_RECMON\", 1)",
    "  end",
    "end"
  ];
  for (const [group, sections] of groups) {
    lines.push(`add(${lua(group.toUpperCase())}, 1)`);
    sections.forEach(([, s], i) => lines.push(`add(${lua(s.label)}, ${i === sections.length - 1 ? -1 : 0}, ${lua(rig.ports[s.port] ?? s.port)}, ${s.channel})`));
  }
  lines.push("reaper.Undo_EndBlock(\"lastfm-companion live rig\", -1)", "reaper.TrackList_AdjustWindows(false)", "");
  return lines.join("\n");
}

// ReaScript that opens a rendered song as a mixing session: tempo set, one track per stem, master reference muted.
export function sessionScript(title: string, bpm: number, beatsPerBar: number, stems: { name: string; path: string }[], master?: string): string {
  const lines = [
    `-- ${title}: generated by lastfm-companion (npm run studio)`,
    "reaper.Undo_BeginBlock()",
    `reaper.SetCurrentBPM(0, ${bpm}, true)`,
    `reaper.SetTempoTimeSigMarker(0, -1, 0, -1, -1, ${bpm}, ${beatsPerBar}, 4, false)`,
    "local function add(name, file, mute)",
    "  reaper.SetEditCurPos(0, false, false)",
    "  reaper.InsertMedia(file, 1)",
    "  local track = reaper.GetTrack(0, reaper.CountTracks(0) - 1)",
    "  reaper.GetSetMediaTrackInfo_String(track, \"P_NAME\", name, true)",
    "  if mute then reaper.SetMediaTrackInfo_Value(track, \"B_MUTE\", 1) end",
    "end",
    ...stems.map(s => `add(${lua(s.name)}, ${lua(s.path)})`),
    ...(master ? [`add("MASTER REFERENCE", ${lua(master)}, true)`] : []),
    `reaper.Undo_EndBlock(${lua(`lastfm-companion: ${title}`)}, -1)`,
    ""
  ];
  return lines.join("\n");
}
